(deftheme eldritch
  "Created 2024-04-13.")

(custom-theme-set-faces
 'eldritch
 '(cursor ((t (:background "#323449"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#04d1f9"))))
 '(homoglyph ((t (:foreground "#04d1f9"))))
 '(minibuffer-prompt ((t (:foreground "#04d1f9"))))
 '(highlight ((t (:background "darkviolet"))))
 '(region ((t (:extend t :background "#323449"))))
 '(shadow ((t (:foreground "#a48cf2"))))
 '(secondary-selection ((t (:background "#323449" :extend t))))
 '(trailing-whitespace ((t (:background "#f16c75"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#f7c67f"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#7081d0"))))
 '(font-lock-constant-face ((t (:foreground "#37f499"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face :foreground "#f7c67f"))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit font-lock-function-name-face))))
 '(font-lock-function-name-face ((t (:foreground "#a48cf2"))))
 '(font-lock-keyword-face ((t (:foreground "#f265b5"))))
 '(font-lock-negation-char-face ((t (:foreground "#04d1f9" :inherit bold))))
 '(font-lock-number-face ((t (:foreground "#f1fc79"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#04d1f9" :inherit bold))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "cyan" :inherit bold))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "cyan" :inherit bold))))
 '(font-lock-string-face ((t (:foreground "#37f499"))))
 '(font-lock-type-face ((t (:foreground "#f1fc79"))))
 '(font-lock-variable-name-face ((t (:foreground "#37f499"))))
 '(vhdl-font-lock-attribute-face ((t (:foreground "cyan"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(button ((t (:inherit (link)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#37f499" :inherit default))))
 '(header-line ((t (:inherit mode-line))))
 '(tooltip ((t (:background "black" :foreground "#bfbfbf"))))
 '(mode-line ((t (:background "black" :foreground "#bfbfbf" :box nil))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#51afef"))))
 '(mode-line-highlight ((((supports :box t) (class color) (min-colors 88)) (:box (:line-width (2 . 2) :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:background "#1e1e1e" :foreground "#525252" :box nil))))
 '(isearch ((t (:inherit lazy-highlight :weight bold))))
 '(isearch-fail ((t (:weight bold :foreground "black" :background "#f16c75"))))
 '(lazy-highlight ((t (:background "#387aa7" :foreground "#dfdfdf" :weight bold))))
 '(match ((t (:background "black" :foreground "#37f499" :weight bold))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(line-number ((t (:inherit default :foreground "#f1fc79" :slant italic :weight normal))))
 '(custom-comment ((t (:background "#6c6c6c" :foreground "#bfbfbf"))))
 '(warning ((t (:foreground "#f7c67f"))))
 '(whitespace-tab ((t (:background "#212337" :foreground "darkgray"))))
 '(lsp-face-highlight-textual ((t (:inherit highlight)))))

(provide-theme 'eldritch)
